### ISSUE TITLE
[버그 🐛] 42header missing !

### ISSUE THREAD

**Issue by stripy1026** [cub3d-project-Backrooms/cub3d#5]
### 오류 종류

기타 예상하지 못한 동작

### 한 줄 요약

Need to apply 42header all in source and header files.

### 발생 과정

```Markdown
norminette * in project root directory.
```

### 오류 상태

원인 발견함, 해결 방법 있음

**Comment by scarf005** [comment]
깃 로그 관리할때 힘들어져서 헤더는 되도록이면 마지막에 추가하려고 합니다
[다음 확장 프로그램](https://marketplace.visualstudio.com/items?itemName=nakamo326.42-header-oneshot)을 통해 해결할수 있읍니다
