### ISSUE TITLE
[기능 추가 ⭐] 동서남북별로 다른 텍스처 보이기

### ISSUE THREAD

**Issue by scarf005** [cub3d-project-Backrooms/cub3d#8]
### 기능 종류

수학 기능/그래픽 기능

### 한 줄 요약

step 구조체의 `is_hit_y_side`와 `y_sign`, `x_sign`으로 구현

### 관련 코드

```C
int texnum;
if (step.is_hit_y_side)
	texnum = 1 + (step.y_sign == 1);
else
	texnum = 3 + (step.x_sign == 1);
```

**Comment by stripy1026** [comment]
해결 완료
<img width="641" alt="Screen Shot 2022-04-20 at 3 17 40 PM" src="https://user-images.githubusercontent.com/62825700/164163123-d79f7944-9f35-425a-bee6-8105af786227.png">

**Comment by scarf005** [comment]
굳굳
나중에 풀 리퀘스트에도 이슈 연결해주세요

**Comment by stripy1026** [comment]
Roger !
